server:
  port: 3030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: varun
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000